//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2024. 11. 30. 14:29:45
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Models
{
    public partial class enTelefonszam {

        public enTelefonszam()
        {
            OnCreated();
        }

        public int Id { get; set; }

        public string Szam { get; set; }

        public int enSzemelyId { get; set; }

        public virtual enSzemely enSzemely { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
